import { type Metadata } from 'next'

const HOSTING_URL = process.env.NEXT_PUBLIC_HOSTING_URL ?? '/'
const TwitterUser = 'polpenaloza'

type Props = {
  description?: string
  title?: string
  url?: string
}

export async function seoGenerateMetadata({
  title = '',
  url = HOSTING_URL,
}: Props): Promise<Metadata> {
  const imageUrl = `${url}metaimage.webp`

  const description = 'Generated by create-t3-app, build by polpenaloza'

  return {
    title: {
      template: `${title} | %s`,
      default: title,
    },
    referrer: 'origin-when-cross-origin',
    generator: 'Next.js',
    description,
    creator: 'polpenaloza',
    abstract: description,
    appleWebApp: true,
    applicationName: 'X-Clone pet project',
    assets: [HOSTING_URL],
    alternates: {
      canonical: url,
    },
    keywords:
      'nextjs, pet project, x-clone, twitter clone, twitter, clone, polpenaloza',
    manifest: '/manifest.json',
    icons: {
      icon: '/favicon.ico',
      shortcut: '/logo.png',
      apple: '/favicon.png',
      other: {
        rel: 'apple-touch-icon-precomposed',
        url: '/apple-touch-icon-precomposed.png',
      },
    },
    robots: {
      index: false,
      follow: true,
      nocache: true,
      googleBot: {
        index: true,
        follow: false,
        noimageindex: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      creator: `@${TwitterUser}`,
      site: TwitterUser,
    },
    other: {
      publishedTime: new Date().toISOString(),
    },
    openGraph: {
      images: [{ url: imageUrl }],
      type: 'website',
      description,
      locale: 'en_US',
      siteName: title,
      title: {
        template: `%s | ${title}`,
        default: title,
      },
      url,
    },
    viewport: {
      width: 'device-width',
      initialScale: 1,
      maximumScale: 1,
    },
    verification: {
      google: 'google',
    },
    appLinks: {
      web: {
        url,
        // eslint-disable-next-line camelcase
        should_fallback: true,
      },
    },
    bookmarks: [url],
    category: 'technology',
  }
}
