# .github/actions/node/action.yml

name: "Node Cache restoration"
description: "Setup a NodeJS environment and restore node modules cache"

inputs:
  node-version:
    description: "Node version to use, default to (18.x)"
    required: true
    default: 18.12.0
outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.pnpm-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          node-modules-${{ runner.os }}-pnpm-
    - shell: bash
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install
