# .github/actions/node/action.yml

name: "Node Cache restoration"
description: "Setup a NodeJS environment and restore node modules cache"

inputs:
  node-version:
    description: "Node version to use, default to (14.x)"
    required: true
    default: 14.17.4
outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.yarn-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node-modules-${{ runner.os }}-yarn-
    - shell: bash
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --silent
