module.exports = {
  extends: [
    'next',
    'turbo',
    'prettier',
    'next/core-web-vitals',
    'plugin:jsx-a11y/recommended',
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
  ],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'simple-import-sort', 'prettier'],
  rules: {
    '@next/next/no-html-link-for-pages': 'off',
    '@typescript-eslint/no-unused-vars': [
      2,
      {
        args: 'after-used',
        argsIgnorePattern: '^_',
        ignoreRestSiblings: true,
      },
    ],
    '@typescript-eslint/no-explicit-any': [1, { ignoreRestArgs: true }],
    'newline-after-var': 'error',
    'no-console': [2, { allow: ['error'] }],
    'no-debugger': 'error',
    'no-duplicate-imports': 'error',
    'no-empty-function': 'error',
    'no-irregular-whitespace': 'error',
    'no-trailing-spaces': 'error',
    'prefer-const': 'error',
    'react/jsx-key': 'off',
    'simple-import-sort/exports': 'error',
    'simple-import-sort/imports': 'error',
    camelcase: 'error',
  },
}
