name: Verify Pull Request

on:
  pull_request:
    branches:
      - main
      - '!dependabot/**'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Run
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: ./.github/actions/node

      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   if: failure()

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restoring Node.js
        uses: ./.github/actions/node

      - name: Lint Code
        run: yarn lint
        env:
          CI: true

      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   if: failure()

      # - name: Slack Success Notification
      #   uses: ./.github/actions/slack-success
      #   if: success()

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restoring Node.js
        uses: ./.github/actions/node

      - name: Build
        run: yarn build
        env:
          CI: true

      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   if: failure()

      # - name: Slack Success Notification
      #   uses: ./.github/actions/slack-success
      #   if: success()
