name: Verify Pull Request

on:
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: "prisma://accelerate.prisma-data.net/?api_key=abc123"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "nextauth-secret"
  GITHUB_CLIENT_ID: "github-client-id"
  GITHUB_CLIENT_SECRET: "github-client-secret"
  GOOGLE_CLIENT_ID: "google-client-id"
  GOOGLE_CLIENT_SECRET: "google-client-secret"
  UPSTASH_REDIS_REST_URL: "redis://localhost:6379"
  UPSTASH_REDIS_REST_TOKEN: "redis-rest-token"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Run
        uses: styfle/cancel-workflow-action@0.12.0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: ./.github/actions/node
      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   if: failure()

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restoring Node.js
        uses: ./.github/actions/node
      - name: Lint Code
        run: pnpm lint
        env:
          CI: true
      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   if: failure()

      # - name: Slack Success Notification
      #   uses: ./.github/actions/slack-success
      #   if: success()

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restoring Node.js
        uses: ./.github/actions/node
      - name: Build
        run: pnpm build
        env:
          CI: true
      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   if: failure()
      # - name: Slack Success Notification
      #   uses: ./.github/actions/slack-success
      #   if: success()
