name: Verify Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - development
      - feat/*
      - release/*
      - testing
      - production

jobs:
  Setup:
    name: Verify Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn

  Lint:
    name: Linters run
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn

      - name: Lint Code
        run: yarn lint

  Build:
    name: Build run
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
