name: Release
run-name: ${{ github.actor }} is automatically releasing 🚀

on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
      - name: 'Generate token'
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: 'Verifying the signatures'
        run: pnpm audit signatures

      - name: Perform Release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: npx semantic-release

      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   if: failure()

      # - name: Slack Success Notification
      #   uses: ./.github/actions/slack-success
      #   if: success()
